# Generated by Django 5.1.3 on 2024-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazeres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Completa')], default='P', max_length=1),
        ),
    ]
